
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 13 10:43:51 CDT 2022
//----------------------------------------------------

package proyecto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Entero = 2;
  public static final int Boleano = 4;
  public static final int Exponente = 17;
  public static final int Ademas = 10;
  public static final int Apertura = 24;
  public static final int LlaveAC = 22;
  public static final int Arroba = 33;
  public static final int Cerradura = 25;
  public static final int Para = 6;
  public static final int Division = 21;
  public static final int Flotante = 3;
  public static final int Cadena = 5;
  public static final int Publico = 12;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Caso = 35;
  public static final int Linea = 14;
  public static final int Op_R = 26;
  public static final int ERROR = 37;
  public static final int Op_L = 27;
  public static final int CerrarL = 23;
  public static final int Op_I = 29;
  public static final int Op_B = 28;
  public static final int Identificador = 30;
  public static final int Si = 8;
  public static final int Salida = 36;
  public static final int Resta = 19;
  public static final int DoblePunto = 34;
  public static final int Sino = 9;
  public static final int Mientras = 11;
  public static final int Multiplicacion = 20;
  public static final int Decimal = 32;
  public static final int Inicial = 13;
  public static final int Numero = 31;
  public static final int Suma = 18;
  public static final int Igual = 16;
  public static final int Cambio = 7;
  public static final int Comillas = 15;
}

