
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 25 11:35:51 CST 2022
//----------------------------------------------------

package proyecto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Entero = 2;
  public static final int Boleano = 4;
  public static final int Exponente = 18;
  public static final int Ademas = 11;
  public static final int Apertura = 25;
  public static final int LlaveAC = 23;
  public static final int Arroba = 34;
  public static final int Cerradura = 26;
  public static final int Para = 7;
  public static final int Division = 22;
  public static final int Flotante = 3;
  public static final int Cadena = 5;
  public static final int Publico = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Texto = 6;
  public static final int Caso = 36;
  public static final int Linea = 15;
  public static final int Op_R = 27;
  public static final int ERROR = 38;
  public static final int Op_L = 28;
  public static final int CerrarL = 24;
  public static final int Op_I = 30;
  public static final int Op_B = 29;
  public static final int Identificador = 31;
  public static final int Si = 9;
  public static final int Salida = 37;
  public static final int Resta = 20;
  public static final int DoblePunto = 35;
  public static final int Sino = 10;
  public static final int Mientras = 12;
  public static final int Multiplicacion = 21;
  public static final int Decimal = 33;
  public static final int Inicial = 14;
  public static final int Numero = 32;
  public static final int Suma = 19;
  public static final int Igual = 17;
  public static final int Cambio = 8;
  public static final int Comillas = 16;
}

